kagent-dev/kagent

CONTRIBUTION.md
DEVELOPMENT.md

* Broken discord link
* Unclosed codeblock

(docs) small updates for readmes

---

python/src/kagent/tools/docs/query_documentation.py

fix doc query tool to fallback to api key from env variable

---

helm/templates/argo-rollouts-agent.yaml

Fix the Argo Rollouts agent system prompt formatting (see: https://kagent.dev/agents/argo-rollouts-conversion-agent)

Fix argo rollouts system prompt formatting

---

ui/src/components/create/ToolsSection.tsx

fix the issue with tool configuration not being persisted

---

README.md

Adjust README to contain links to the project site documentation.

Add links to project site documentation

---

ui/src/app/agents/[agentId]/chat/page.tsx

Implement error handling in ChatLayout component to display error states for agent retrieval failures.
Closes #197

fix: show an error if agentID is invalid or not found

---

go/controller/internal/httpserver/errors/errors.go
go/controller/internal/httpserver/handlers/health.go
go/controller/internal/httpserver/handlers/helpers.go
go/controller/internal/httpserver/handlers/modelconfig.go
go/controller/internal/httpserver/handlers/runs.go
go/controller/internal/httpserver/handlers/sessions.go
go/controller/internal/httpserver/handlers/teams.go
go/controller/internal/httpserver/handlers/tools.go
go/controller/internal/httpserver/handlers/toolservers.go
go/controller/internal/httpserver/middleware.go
go/controller/internal/httpserver/middleware_error.go
go/controller/internal/httpserver/server.go

This commit adds detailed logging to all REST API handlers in the controller:
- Add structured logging with context information (operation type, user ID, resource IDs)
- Implement different log levels (Info for important events, V(1) for detailed operations)
- Enhance error logging with detailed context
- Improve validation error messages in the team creation handler
- Create consistent logging patterns across all handlers
- Add logging to helper functions for complete traceability
The changes follow best practices by using request-scoped loggers that carry request context, allowing for better debugging and monitoring in production.
Fixes #203

feat(controller): add comprehensive logging to HTTP handlers

---

python/Dockerfile

Prevent pypi.org to be accessed at runtime

---

ui/src/components/create/ToolsSection.tsx
ui/src/lib/__tests__/toolUtils.test.ts
ui/src/lib/toolUtils.ts

fix issue with wrong tools being identified

---

go/cli/internal/cli/install.go

This is implementation of https://github.com/kagent-dev/kagent/pull/252#discussion_r2051881145 to clean CRDs when uninstalling kagent.

clean CRDs when uninstalling kagent

---

go/controller/cmd/main.go
helm/kagent/templates/deployment.yaml

fix: deployment to custom namespace causes errors

---

go/config/rbac/role.yaml
go/controller/internal/httpserver/handlers/handlers.go
go/controller/internal/httpserver/handlers/helpers.go
go/controller/internal/httpserver/handlers/memory.go
go/controller/internal/httpserver/handlers/modelconfig.go
go/controller/internal/httpserver/handlers/providers.go
go/controller/internal/httpserver/server.go
ui/src/app/actions/memories.ts
ui/src/app/actions/providers.ts
ui/src/app/actions/teams.ts
ui/src/app/agents/new/page.tsx
ui/src/app/memories/new/page.tsx
ui/src/app/memories/page.tsx
ui/src/app/models/new/page.tsx
ui/src/components/AgentsProvider.tsx
ui/src/components/Header.tsx
ui/src/components/create/MemorySelectionSection.tsx
ui/src/components/onboarding/steps/ModelConfigStep.tsx
ui/src/components/sidebars/AgentDetailsSidebar.tsx
ui/src/components/ui/table.tsx
ui/src/lib/types.ts
ui/src/types/datamodel.ts

+ required backend http handlers and a missing role.yaml that includees memories resource

Add UI for memory

---

python/src/kagent/tools/argo/_kubectl_argo_rollouts.py
python/src/kagent/tools/istio/_istioctl.py
python/src/kagent/tools/k8s/_kubectl.py

Fixed #308 
Pydantic2 explicitly requires any optional types to be set to a default value: 
https://docs.pydantic.dev/dev/migration/#required-optional-and-nullable-fields

Optional types must be set to a default value (e.g. None)

---

ui/cypress.config.ts
ui/cypress/e2e/smoke.cy.ts
ui/package-lock.json
ui/package.json
ui/src/app/agents/[agentId]/chat/[chatId]/page.tsx
ui/src/app/agents/[agentId]/chat/layout.tsx
ui/src/app/agents/[agentId]/chat/page.tsx
ui/src/components/chat/ChatInterface.tsx
ui/src/components/chat/TruncatableText.tsx
ui/src/components/sidebars/AgentDetailsSidebar.tsx
ui/src/components/sidebars/AgentSwitcher.tsx
ui/src/components/sidebars/GroupedSessions.tsx
ui/src/components/sidebars/RunItem.tsx
ui/src/components/sidebars/SessionsSidebar.tsx
ui/src/lib/useChatStore.ts

This fixes the scrolling issue (#283) (e.g. scrolls automatically to the bottom now when streaming). I've also refactored the chat pages to reduce the number of requests being sent to the backend. Lastly, started basic UI testing -- not much for now, but at least a start and something that can be run locally for now.

Fix scrolling + various other fixes

---

ui/src/components/create/SelectToolsDialog.tsx
ui/src/components/create/ToolsSection.tsx
ui/src/components/sidebars/AgentDetailsSidebar.tsx

fix the issue where only first tool in the mcpserver entry was displayed

---

ui/src/components/onboarding/steps/ModelConfigStep.tsx
ui/src/lib/constants.ts

fix(ui): enable setting the base URL for Ollama models in the wizard

---

helm/kagent-crds/templates/kagent.dev_modelconfigs.yaml
helm/kagent-crds/templates/kagent.dev_toolservers.yaml
helm/kagent/templates/cilium-crd-agent.yaml
helm/kagent/values.yaml
ui/package-lock.json
ui/package.json
ui/src/components/chat/TruncatableText.tsx

Add Cilium CRD agent

---

ui/src/app/models/new/page.tsx

fix the issue where values were not treated as numbers

---

python/Dockerfile

fix the tools folder typo

---

go/cli/cmd/kagent/main.go
go/cli/internal/cli/a2a.go
go/cli/internal/cli/bug_report.go
go/cli/internal/cli/dashboard.go
go/cli/internal/cli/dashboard_darwin.go
go/cli/internal/cli/get.go
go/cli/internal/cli/install.go
go/cli/internal/cli/invoke.go
go/cli/internal/cli/utils.go
go/cli/internal/cli/version.go

This PR furthers the work to create parity between the interactive and non-interactive versions of the CLI.

Non interactive cli [Dashboard, Get]

---

ui/eslint.config.mjs
ui/src/app/memories/new/page.tsx
ui/src/app/memories/page.tsx
ui/src/components/ToolDisplay.tsx
ui/src/components/chat/ChatInterface.tsx
ui/src/components/chat/ToolCallDisplay.tsx
ui/src/components/sidebars/GroupedChats.tsx

Fixes issue with tool display

---

go/controller/internal/autogen/autogen_api_translator.go
ui/src/app/agents/new/page.tsx
ui/src/components/create/MemorySelectionSection.tsx
ui/src/components/create/ModelSelectionSection.tsx
ui/src/components/create/SystemPromptSection.tsx

remove the automatically added system prompt

---

go/cli/internal/cli/install.go

fixes https://github.com/kagent-dev/kagent/issues/468

fix:(cli) line breaks in output (install)

---

.github/workflows/ci.yaml
.github/workflows/lint-python.yaml
.github/workflows/tools_tests.yaml

This reverts commit c7ab042aa326112c079af779ebabe2fed42d7844.

Revert "fix-workflow-target (#527)"

---

python/src/autogenstudio/database/db_manager.py

https://github.com/kagent-dev/kagent/issues/546
Tested with ToolServer
```yaml
apiVersion: kagent.dev/v1alpha1
kind: ToolServer
metadata:
name: api.githubcopilot.com
namespace: kagent
spec:
config:
streamableHttp:
headers:
Authorization: "Bearer TOKEN"
sseReadTimeout: 5m0s
timeout: 15s
url: https://api.githubcopilot.com/mcp/
description: |
GitHub Copilot is an AI-powered code completion tools
```

Fix streamableHttp Tools DB format issue

---

CODEOWNERS

this misconfiguration was spotted in #555

chore(CODEOWNERS): add owners for root-level files

---

ui/src/app/servers/page.tsx

toggle servers, sort them

---

helm/kagent/templates/toolserver-grafana.yaml
helm/kagent/templates/toolserver-kagent.yaml
helm/kagent/tests/toolserver_test.yaml

fix: grafana toolserver

---

helm/kagent/templates/controller-deployment.yaml
helm/kagent/templates/ui-deployment.yaml
helm/kagent/tests/controller-deployment_test.yaml
helm/kagent/tests/ui-deployment_test.yaml
helm/kagent/values.yaml
helm/tools/querydoc/templates/deployment.yaml
helm/tools/querydoc/tests/deployment_test.yaml
helm/tools/querydoc/values.yaml

https://github.com/kagent-dev/kagent/issues/717

feat: Add support for nodeSelector and tolerations

---

ui/package-lock.json
ui/package.json

upgrading all libs from PRs - #787, #788, #777, #776

fix snyk issues

---

go/cli/cmd/kagent/main.go

This PR introduces actually cancelling the root context when receiving an OS signal such as CTRL+C so that the context is cancelled throughout the `kagent` CLI

fix(install): cancel root context when receiving an OS signal

---

go/internal/controller/reconciler/reconciler.go

OK, the PR does a little more than the title mentions - sorry :sweat_smile: Started out trying to fix a couple copy/pasta errors but then things evolved... Will comment in-line where I think things may need further justification.

refactor(controller): fix logging during remote mcp server reconciliation

---

go/go.mod
go/go.sum
go/internal/controller/reconciler/reconciler.go
go/internal/httpserver/auth/authn.go
go/internal/httpserver/auth/authn_test.go
go/internal/httpserver/handlers/helpers.go
go/internal/httpserver/handlers/sessions.go
go/internal/httpserver/handlers/sessions_test.go
go/internal/httpserver/server.go
go/pkg/auth/auth.go

- make session interface
- bump `trpc.group/trpc-go/trpc-a2a-go` and remove replace directive
- simplify Authenticate

various auth cleanup

---

go/internal/controller/a2a/a2a_reconciler.go
go/internal/httpserver/auth/authn.go
go/pkg/auth/auth.go

Exposes the upstream principal to UpstreamAuth

cleanup: provide upstream principal to upstream auth

---

go/internal/controller/translator/adk_api_translator.go

fix: update azure endpoint env var

---

go/cli/internal/cli/install.go

This just gives a slightly better error message for users with missing deps or a misconfigured shell. 
fixes #881

check helm is available before install

---

go/internal/adk/types.go
go/internal/controller/translator/adk_api_translator.go
go/internal/controller/translator/testdata/outputs/agent_with_http_toolserver.json
go/internal/controller/translator/testdata/outputs/agent_with_mcp_service.json
go/internal/controller/translator/testdata/outputs/agent_with_nested_agent.json
go/internal/controller/translator/testdata/outputs/anthropic_agent.json
go/internal/controller/translator/testdata/outputs/basic_agent.json
go/internal/controller/translator/testdata/outputs/ollama_agent.json
python/packages/kagent-adk/src/kagent/adk/models/_openai.py
python/packages/kagent-adk/src/kagent/adk/types.py

support sending custom headers from model to litellm
@EItanya - should extra_headers be set to all model types?

support litellm extra_headers

---

python/packages/kagent-adk/src/kagent/adk/_agent_executor.py

fixes #911 
The runner.close was tearing down MCP sessions from the wrong task; that triggered cancel-scope errors and a cancellation storm causing the CPU to get to 1000m and stay there. also wrapping the generator with aclosing, so it cleans up the generator safely.

fixes [BUG] kagent 100% CPU and not responding well to queries #911

---

contrib/security/security-self-assessment.md
security-self-assessment.md

xref: https://github.com/kagent-dev/community/issues/8

security: introduce self-assessment for CNCF incubation

---

go/cli/internal/cli/agent/invoke.go

Added logic to handle agent names with namespaces.

Handle agent names with namespace in invoke.go
