README.md
Everyone's favorite type of PR: tackling some mispelled words in a README. Fixes the "Kubernets" spelling.
=> README: s/Kubernets/Kubernetes

README.md
This makes sense as the pod won't run if the key is missing
=> docs: set openai key in the quickstart command

ui/src/components/AddServerDialog.tsx
Fixed #187 
Preview command color from the preview components in /kagent/ui/src/components/AddServerDialog.tsx foxed for dark mode.
=> Fixed Style Command Preview New Tool Dark Mode

python/.gitignore, python/src/kagent/tools/docs/query_documentation.py
Fix the incorrect "product_name" in the dbs themselves. When we do a QueryTool query, we filter by product_name and the names don't line up without this PR.
=> fix product_name for the dbs which dont match whats in the db themselves

go/controller/internal/httpserver/handlers/modelconfig.go, go/controller/internal/httpserver/handlers/teams.go, go/controller/internal/httpserver/handlers/toolservers.go, go/controller/internal/httpserver/server.go, go/controller/internal/utils/common.go, helm/templates/deployment.yaml
Fixes #191
- Reads the resource namespace from environment variable and removes hardcoded value from code.
- Update the helm deployment controller container to inject namespace as environment variable
=> feat(controller) read DefaultResourceNamespace from the env variable

helm/kagent/templates/argo-rollouts-agent.yaml, helm/kagent/templates/helm-agent.yaml, helm/kagent/templates/istio-agent.yaml, helm/kagent/templates/kube-agent.yaml, helm/kagent/templates/modelconfig.yaml, helm/kagent/templates/observability-agent.yaml, helm/kagent/templates/promql-agent.yaml, helm/kagent/values.yaml
This pr goal is to disable totaly openai model one or multiple instead that are local (like ollama)
This also unlock the ability to use different model depending of the agent and thus be able to compare them.
```yaml
openai:
enabled: false
contrib:
agents:
k8s:
enabled: true
modelConfigRef: ollama-model-config # ModelConfig for ollama needs to be define
helm:
enabled: true
modelConfigRef: anthropic-model-config # ModelConfig for anthropic needs to be define
```
=> Allow to disable completely openai model

go/controller/internal/autogen/autogen_reconciler.go
This Pull Request closes [issue #293](https://github.com/kagent-dev/kagent/issues/293)!
With this change, agent lifecycle events are now **cleanly and consistently logged**, with **no more unexpected exceptions** cluttering the output.  
It’s now easier than ever to understand what’s happening — whether you’re creating, updating, or deleting agents!
- **When an agent is created:**
```shell
2025-04-29T00:38:35Z	INFO	reconcile	New agent created	{"namespace": "kagent", "name": "promql-agent", "generation": 1}
2025-04-29T00:38:35Z	INFO	reconcile	New agent created	{"namespace": "kagent", "name": "argo-rollouts-conversion-agent", "generation": 1}
2025-04-29T00:38:35Z	INFO	reconcile	New agent created	{"namespace": "kagent", "name": "helm-agent", "generation": 1}
```
- **When an agent is …
=> fix: improve agent reconciliation implementation

.gitignore, go/autogen/client/run.go, go/autogen/client/types.go, go/cli/cmd/kagent/main.go, go/cli/internal/cli/chat.go, go/cli/internal/cli/get.go
Fixes a couple of small issues.
* `run chat` with args used to result in a SIGSEGV because while getting the `team`, params were passed in the wrong order so we got a **nil** object for team. Also the `-s` flag for session was not respected. 
```
kagent >> run chat blah
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x48 pc=0x1026587c8]
goroutine 1 [running]:
github.com/kagent-dev/kagent/go/cli/internal/cli.ChatCmd.func1(...)
/Users/nim/src/github.com/nimishamehta5/kagent/go/cli/internal/cli/chat.go:109
github.com/kagent-dev/kagent/go/cli/internal/cli.ChatCmd.Collect[...].func4-range3(...)
...
```
Now, with an incorrect chat name, it prompts the user to select from the available teams:
```
kagent >> run chat …
```
=> CLI: Minor fixes and improvements

ui/src/app/agents/new/page.tsx
When navigating directly from editing an agent to creating a new one without refreshing the page, the form state isn't being properly reset. This creates an issue where form field values from the agent previously selected for edit mode would persist when creating a new agent.
- Moved route parameters from inside the component to being passed as props
- Added a unique key to the AgentPageContent element based on the current mode (edit/create) and agent ID
- This forces component to remount when switching between create/edit modes, ensuring clean state initialization
=> fix(ui): force remount of AgentPageContent when switching between create and edit mode

helm/kagent/values.yaml
fix the following warning when new env are defined
```
coalesce.go:286: warning: cannot overwrite table with non table for kagent.kagent.app.env (map[])
```
=> Fix warning from values.yaml

go/controller/internal/httpserver/handlers/invoke_test.go, python/src/autogenstudio/web/routes/sessions.py
Previous change to Run ID: https://github.com/kagent-dev/kagent/pull/320 (convert from `string` to `int`) broke the List Session Runs API.
This attempts to make both the APIs (List Session Runs & Get Run) work.
In the autogenstudio server, we will update the `list_session_runs` API to also return the run IDs as ints to stay consistent with how the other APIs are implemented.
Before:
```
kagent >> get run 1
{
"id": 1,
"session_id": 1,
"created_at": "2025-05-06T19:44:13.690563",
"status": "error",
...
kagent >> get run
Failed to get runs: error unmarshaling into result: json: cannot unmarshal string into Go struct field Run.runs.id of type int
```
After:
```
kagent >> get run 1
{
"id": 1,
"session_id": 1,
"created_at": "2025-05-06T19:44:13.690563",
"status": "error",
...
kagent >> get run …
```
=> CLI: Fix get run without run ID marshaling

go/Makefile, go/config/crd/bases/kagent.dev_modelconfigs.yaml, go/config/crd/bases/kagent.dev_toolservers.yaml, go/controller/api/v1alpha1/autogenmodelconfig_types.go, go/controller/api/v1alpha1/toolserver_types.go
Small quality of life improvement to interact with common Kagent CRs.
Removed refs to Kustomize from the Makefile, as that flow is no longer used.
=> Add shortNames to CRDs, remove Makefile refs to kustomize

helm/kagent/templates/_helpers.tpl, helm/kagent/templates/argo-rollouts-agent.yaml, helm/kagent/templates/clusterrolebinding.yaml, helm/kagent/templates/deployment.yaml, helm/kagent/templates/helm-agent.yaml, helm/kagent/templates/istio-agent.yaml, helm/kagent/templates/kgateway-agent.yaml, helm/kagent/templates/kube-agent.yaml, helm/kagent/templates/modelconfig.yaml, helm/kagent/templates/observability-agent.yaml, helm/kagent/templates/promql-agent.yaml, helm/kagent/templates/secret.yaml, helm/kagent/templates/service.yaml, helm/kagent/templates/serviceaccount.yaml, helm/kagent/values.yaml
Ensures that rendered manifests have `namespace` set as per the value of the `namespace` flag used when running `helm template` (or optionally overriden via `values.yaml`). Enables deployment of manifests with commands like:
```
helm template --release-name kagent --namespace kagent . | kubectl apply -f -
```
FWIW, this is a fairly common pattern across a number of open source charts. Several examples can be seen within the [bitnami charts](https://github.com/search?q=repo%3Abitnami%2Fcharts%20namespaceOverride&type=code).
=> Template namespace for resources produced by `kagent` Helm chart

python/pyproject.toml, python/uv.lock
Autogen just released a new version (that has the mcp fix we've been waiting for). We can now stop depending on our fork and just use the release version of autogen instead.
=> removing dep on our autogenfork

ui/src/app/agents/new/page.tsx
Disables the input field in Edit mode, because if edited the update request will fail as it cannot find the agent.
=> [FIX] disable agent name input when in edit mode

helm/kagent/templates/_helpers.tpl
Recently the PR went in to switch agents over to the new helm format. This unfortunately broke the RBAC templates for some of those agents silently. This fixes that.
=> [FIX] name template for sub-charts

ui/src/components/onboarding/OnboardingWizard.tsx
fixes - #352 
Replaced absolute positioning with flex layout (justify-between, `px-6`, `pb-4`, `pt-2`) to reposition. cc : @peterj
=> fix: reposition "Skip wizard" link in onboarding wizard

go/cli/cmd/kagent/main.go
The `kagent get --help` message is not descriptive enough to understand what resource types can be gotten.
Restructuring the `kagent get` cobra command to set up the 'resource type' as subcommands instead of internally-defined switch-case.
This:
1. Allows for a more descriptive `help` (automatically).
2. Makes it easier to extend this (ifever done), where added resource types would be added as subcommands and automatically be referenced in the `help`.
3. Allows the `get` and the subsequent resource type to have a single responsibility.
```
$ go run go/cli/cmd/kagent/main.go get --help
Get a kagent resource
Usage:
kagent get [flags]
kagent get [command]
Available Commands:
agent       Get an agent or list all agents
run         Get a run or list all runs
session     Get a session or list …
```
=> [CLI] Use subcommands for `kagent get`

go/autogen/client/team.go, go/controller/internal/autogen/autogen_reconciler.go, go/controller/internal/httpserver/handlers/teams.go, go/test/e2e/e2e_test.go, helm/kagent/templates/deployment.yaml
This PR properly hooks up the failure statuses for agents. They still aren't as useful as they could be, but they are at least pointing in the right direction now :)
for example:
```
status:
conditions:
- lastTransitionTime: "2025-06-24T19:59:30Z"
message: 'failed to translate agent kagent/everything: tool add not found in discovered
tools in ToolServer kagent/everything'
reason: AgentReconcileFailed
status: "False"
type: Accepted
observedGeneration: 1
```
=> fix(controller): fix status reconcile

README.md
- Fixed broken documentation links in REAME.md file that were returing 404 errors. The "Quick Start" and "Instllation guide" links have been updated to point to the correct documentation resources.
=> docs: fix documentation links in README

ui/package-lock.json, ui/package.json, ui/src/components/chat/TruncatableText.tsx
Regression introduced in #357 - not sure what the intention there was, though, as from what I can tell it doesn't seem related to the rest of the changes in that PR. cc @peterj 
Currently:
vs with fix
(Note difference in links in bottom-left of screenshots above)
=> fix(ui): ensure markdown URLs render correctly

ui/src/lib/messageHandlers.ts
Args do not display in active chat sessions at present due to a mismatch between the use of `arguments` and `args` (they display fine when looking at chat history). Card uses `.args` [here](https://github.com/kagent-dev/kagent/blob/3022b2458df9f563f9ea031e736461848f170e75/ui/src/components/ToolDisplay.tsx#L106C101-L106C114). Also, note that JSON.stringify is applied when rendering the `Card` since #679.
Currently:
vs with fix
=> fix(ui): correctly display args for tool calls in chat

.gitignore, go/pkg/client/README.md
Fixes KAgent client README documentation. Renames Teams to Agents.
=> fix: update client README with correct API usage and method names

Makefile, scripts/kind/setup-metallb.sh
This PR makes the project's Makefile and setup scripts more portable, enabling them to work on systems with non-standard bash locations (e.g. NixOS).
=> Make shebang more portable

helm/kagent/templates/controller-deployment.yaml, helm/kagent/values.yaml, python/packages/kagent/src/kagent/cli.py
This PR makes it configurable to emit input/output messages as events if OTel logging is configured to be compliant with https://github.com/open-telemetry/semantic-conventions/pull/2179. By default, input/output is being emitted as span attributes.
Fixes https://github.com/kagent-dev/kagent/issues/637
=> Make it possible to emit input/output as log events

go/cli/internal/cli/dashboard.go, go/cli/internal/cli/dashboard_darwin.go
Dashboard command was referencing the old service name 'kagent' instead of the correct UI service name 'kagent-ui'
=> fix(cli): update dashboard service name to kagent-ui

python/packages/kagent/src/kagent/cli.py
This PR removes the console exporter that was used during development. You can still push OTel data to an OTel collector with `debugexporter` configured to see the raw data.
=> fix: Remove console exporter

ui/Dockerfile, ui/conf/nginx.conf
Noticed an issue when attempting to build and run the containers from main branch. 
The kagent-ui pod wasn’t coming online because nginx exited on startup with a permission error writing its PID file to `/run/nginx.pid`.
Observed logs:
```
2025-08-13 03:04:43,571 INFO spawned: 'nginx' with pid 209
2025-08-13 03:04:43,581 DEBG 'nginx' stderr output:
nginx: [emerg] open() "/run/nginx.pid" failed (13: Permission denied)
...
2025-08-13 03:04:43,582 WARN exited: nginx (exit status 1; not expected)
```
The kagent-ui pod goes into crash loop and never becomes Ready and the UI is unreachable.
With the container is running nginx as non-root and/or with a read-only root filesystem, `/run` isn’t writable to the nginx process. nginx tries to create `/run/nginx.pid` by default and fails. So this …
=> fix(kagent-ui): write PID to /tmp to avoid permission error

go/internal/httpserver/handlers/agents.go, go/internal/httpserver/handlers/agents_test.go, go/pkg/client/api/types.go, ui/src/components/AgentCard.tsx, ui/src/components/DeleteAgentButton.tsx, ui/src/types/index.ts
This PR implements deployment readiness checking for agents in the UI. Agents are now only clickable and interactive when their deployment is ready, preventing users from attempting to interact with agents that haven't finished their deployment process.
- **Added `deploymentReady` field** to `AgentResponse` API type
- **Implemented status checking logic** in `getAgentResponse()` to check for Ready condition with DeploymentReady reason and status="True"
- **Added comprehensive tests** covering all scenarios: ready/not ready, wrong status, wrong reason
- **Enhanced `AgentCard`** to conditionally enable clickability based on `deploymentReady` status
- **Added visual indicators** for non-ready agents:
- "Not Ready" badge
- Reduced opacity (60%) 
- Gray border
- `cursor-not-allowed` styling
- …
=> feat: wait for agent deployment ready before enabling UI interactions (closes #734)

helm/kagent/templates/modelconfig.yaml
Fixes issue with kagent template logic for default ModelConfig resource. The issue occured because template was using `model.config` but that field only exist on some providers.
Locally you can see this issue if you template the chart
```
helm template oci://ghcr.io/kagent-dev/kagent/helm/kagent | yq 'select(.kind == "ModelConfig")'
Pulled: ghcr.io/kagent-dev/kagent/helm/kagent:0.6.0
Digest: sha256:2f7b505e2474e52aabb5abdb8ba5b529a88b8ba4a23f065c909643b4b3a8dfd6
apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
name: "default-model-config"
namespace: default
labels:
helm.sh/chart: kagent-0.6.0
app.kubernetes.io/name: kagent
app.kubernetes.io/instance: release-name
app.kubernetes.io/version: "0.6.0"
app.kubernetes.io/managed-by: Helm
spec:
provider: "OpenAI"
model: "gpt-4.1-mini" …
```
=> [BUG] fix helm templates for kagent

Makefile, go/go.mod, go/go.sum, scripts/kind/setup-kind.sh, scripts/kind/setup-metallb.sh
When running `make create-kind-cluster` from main branch, the following error occurs
```sh
sh ./scripts/kind/setup-metallb.sh
./scripts/kind/setup-metallb.sh: 4: set: Illegal option -o pipefail
make: *** [Makefile:107: create-kind-cluster] Error 2
```
This PR makes KIND cluster creation idempotent and applies a minor script update to use `bash` over `sh` and shebang update to be more portable. 
Also dynamically resolve the KMCP chart version from the latest GitHub release (strip leading “v”), use it in Helm, and print it in tools output.
=> fix: improve local kind cluster creation process and add kmcp version var

go/Makefile, go/cli/Makefile, go/cli/internal/cli/const.go, go/cli/internal/cli/install.go, go/internal/version/version.go
Fixed issue with CLI's `install` command which was missing the `kmcp-crds`.
`install`: Added kmcp-crd installation step with configurable repo & version.
`uninstall`: Added kmcp-crd uninstallation.
In order to keep this up to date based on `go.mod` I've added the kmcp version information to build flags.
_quick install/uninstall demo of the cli_
https://github.com/user-attachments/assets/87de3ac9-991b-4783-b9d3-aca45dfdc4b0
=> [FIX] Add `kmcp-crds` to cmd installation

helm/kagent/values.yaml
If `apiKey` is set to empty by default, a Secret resources is created.
This PR disable this feature, like that we could use ExternalSecretOperator to manage secrets.
=> feat(helm): do not set apiKey by default

Makefile, helm/kagent-crds/Chart-template.yaml
Kagent requires `McpServers` resource which comes from kmcp project. This pull request adds those crds as a subchart of kagent-crds to make for easier installation UX.
=> [BUG] add kmcp as a subchart to kagent-crds

go/cli/internal/cli/install.go
`kagent install` would construct an invalid `helm upgrade` command due to a missing `--set` parameter.
When invoking `kagent install` (with no specified config params or other `kagent` env vars) & running a `ps aux` in parallel I can see that `kagent` runs the following command 
```go
helm upgrade --install kagent oci://ghcr.io/kagent-dev/kagent/helm/kagent --version 0.6.3 --namespace kagent --create-namespace --wait --history-max 2 --timeout 5m --set providers.default=openAI --set providers.openAI.apiKey=<REDACTED> --set `
```
This command is invalid and errors with `Error: flag needs an argument: --set`. 
The reason that we pass `[]{""}` to `installChart()` is because we obtain the values from [here](https://github.com/kagent-dev/kagent/blob/main/go/cli/internal/cli/install.go#L78): …
=> fix(install): do not add --set for an empty string

python/packages/kagent-adk/pyproject.toml, python/uv.lock
Not exactly sure what the process is here - so feel free to let me know if I've missed anything. Mostly interested in the `a2a-sdk` update, as [`v0.3.1`](https://github.com/a2aproject/a2a-python/releases/tag/v0.3.1) contains [a fix](https://github.com/a2aproject/a2a-python/pull/383) I put through to resolve context cancellation issues that have been plaguing me when testing multi-agent workflows. I did scan the release notes of both projects for breaking changes, and I don't think any of them affected this project's usage of the libraries. Ran the default set of agents locally, and everything seems to work fine.
=> build(deps): bump versions of `google-adk` and `a2a-sdk`

helm/kagent/templates/_helpers.tpl, helm/kagent/values.yaml
Adds `labels` configuration option in values.yaml
- Custom labels are applied to all Kubernetes resources via the `kagent.labels` helper template
- Maintains existing standard labels (app.kubernetes.io/*, helm.sh/chart, etc.)
```yaml
labels:
environment: production
team: platform
```
=> feat(helm): add custom labels support to all Kubernetes resources

ui/src/components/AgentCard.tsx
This PR fixes the issue where agents in "Not Ready" state were completely disabled in the UI, preventing users from editing them to fix the underlying problems.
- **Removed disabled state** from Edit and Delete buttons in `AgentCard.tsx` for Not Accepted/Not Ready agents
- **Updated card styling** to remove the faded appearance (`opacity-60`) and `cursor-not-allowed` for non-ready agents
- **Preserved chat protection** - the Link wrapper for chat navigation is still only applied when `deploymentReady && accepted`
- **Maintained proper filtering** in AgentSwitcher to hide non-ready agents from chat dropdown
- **Edit button is clickable** - users can now edit any agent regardless of status
- **Delete button is clickable** - users can delete any agent regardless of status  
- **Card has …
=> fix(ui): enable editing for Not Accepted/Not Ready agents

ui/src/components/ToolDisplay.tsx
Fixes UI overlap issue where the Arguments dropdown in ToolDisplay component was overlapping with elements below when expanded.
=> fix(ui): prevent Arguments dropdown from overlapping UI elements

python/packages/kagent-adk/src/kagent_adk/models.py
Addresses issue whereby agent->agent calls are currently failing with errors like this in the UI:
``` json
{"id":"call_xx": "name": "transfor_to_agent", "response":{"result": null}}
```
Agent pods show the following errors:
```
ERROR:google_adk.google.adk.agents.remote_a2a_agent:Failed to resolve remote A2A agent kagent__NS__my_agent: Failed to resolve AgentCard from URL http://my-agent.kagent:8080/: HTTP Error 405: Failed to fetch agent card from http://my-agent.kagent:8080/: Client error '405 Method Not Allowed' for url 'http://my-agent.kagent:8080/'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405
```
I guess this was my bad, and it's related to the upgrade in #816.
=> fix(adk): set correct URL for remote agent card

go/internal/database/manager.go
Prevents following error if controller fails to initialise database on startup (e.g. if it happens to run out of memory when loading the db).
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1a3158e]
goroutine 107 [running]:
github.com/kagent-dev/kagent/go/internal/database.(*Manager).Close(0xc00024ea00?)
/workspace/internal/database/manager.go:144 +0xe
github.com/kagent-dev/kagent/go/internal/httpserver.(*HTTPServer).Start.func2()
/workspace/internal/httpserver/server.go:110 +0x116
created by github.com/kagent-dev/kagent/go/internal/httpserver.(*HTTPServer).Start in goroutine 104
/workspace/internal/httpserver/server.go:101 +0x288
```
=> fix(controller): prevent panic on shutdown due to nil pointer

go/cmd/controller/main.go, go/go.mod, go/go.sum, go/internal/controller/reconciler/reconciler.go, go/internal/controller/reconciler/utils/reconciler_utils.go, go/internal/controller/translator/adk_api_translator.go, go/internal/controller/translator/adk_translator_golden_test.go, go/internal/controller/translator/mutate.go, go/internal/controller/translator/testdata/outputs/agent_with_http_toolserver.json, go/internal/controller/translator/testdata/outputs/agent_with_mcp_service.json, go/internal/controller/translator/testdata/outputs/agent_with_nested_agent.json, go/internal/controller/translator/testdata/outputs/anthropic_agent.json, go/internal/controller/translator/testdata/outputs/basic_agent.json, go/internal/controller/translator/testdata/outputs/ollama_agent.json, go/internal/httpserver/handlers/agents.go, go/pkg/app/app.go, go/pkg/translator/adk_api_translator_types.go
adds extension points for downstream forks / extensions of the core kagent code base
depends on https://github.com/kagent-dev/kmcp/pull/78
=> add downstream extension points

python/packages/kagent-adk/src/kagent/adk/converters/error_mappings.py, python/packages/kagent-adk/src/kagent/adk/converters/event_converter.py, python/tests/test_converters/test_event_converter.py
- There's currently a [bug](https://github.com/google/adk-python/blob/14484065c64396cebc4a1dde84d6b8b51439b990/src/google/adk/models/llm_response.py#L133C1-L134C1) in ADK where a valid finish reason ie: `STOP` is passed as the `error_code` in the llm response when there is no content. This results in kagent-adk picking up the valid finish reason as an error and emits a generic `An error occurred during processing` message to the user.
- This PR fixes this issue in kagent-adk and improves the error messaging by only emitting an error status event for completion reasons that represent actual failures.
=> fix: valid STOP completion results in an error being returned 

go/config/crd/bases/kagent.dev_agents.yaml, helm/kagent-crds/templates/kagent.dev_agents.yaml
Diff results from updates to `k8s.io` modules in #864 - although I'm a little puzzled as to what that upgrade had to do with "add[ing] native openai impl to adk" :detective:
=> fix(helm): regenerate CRDs

ui/src/app/actions/agents.ts, ui/src/components/AgentCard.tsx, ui/src/components/AgentGrid.tsx, ui/src/components/Header.tsx, ui/src/components/chat/AgentCallDisplay.tsx, ui/src/components/chat/ToolCallDisplay.tsx, ui/src/components/create/ModelSelectionSection.tsx, ui/src/lib/__tests__/messageHandlers.test.ts, ui/src/lib/messageHandlers.ts, ui/src/lib/toolUtils.ts, ui/src/lib/utils.ts
Fixes #898 .
Adds a dedicated component that shows calls made to the (sub) agents similarly to when we call functions.
=> fix outputs from agent calls

helm/kagent/values.yaml, ui/src/app/a2a/[namespace]/[agentName]/route.ts, ui/src/components/chat/ChatInterface.tsx, ui/src/lib/a2aClient.ts
Whilst API interaction with Agents may use a streaming connection the agents themselves [do not use streaming](https://github.com/kagent-dev/kagent/blob/5c99583b505cbc205bcf1503ffdb1b241abf08c9/python/packages/kagent-adk/src/kagent/adk/converters/request_converter.py#L32) when communicating with the model .Thus, if a model takes longer than 60s to run (looking at you `gpt-5`) then things start timing out. 
This PR:
- increases the default timeout on the A2A streaming connections in the controller to 10mins (this is a thumbsuck number and was chosen to match the [default timeout](https://github.com/google/adk-python/blame/main/src/google/adk/agents/remote_a2a_agent.py#L86) used by Google on non-streaming `RemoteA2AAgent` calls)
- adds a keep-alive implementation to the UI A2A proxy to …
=> Fix UI/streaming timeouts for long running LLM requests

go/internal/httpserver/handlers/sessions.go, python/packages/kagent-adk/src/kagent/adk/_session_service.py
get userid from query param if agent creates a session.
note - in the future we may want to create the session for the agent internally instead of having the agent call create_session.
=> fix: get userid from parameters when agent calls us

helm/kagent/values.yaml
According to https://docs.claude.com/en/docs/about-claude/model-deprecations the claude-3-sonnet-20240229 model was retired on July 21, 2025 and should be replaced with a currently 'Active' model. I suggested claude-3-5-haiku-20241022 for cost reasons. But the official replacement for claude-3-sonnet-20240229 is claude-sonnet-4-20250514 and could also be used
=> replace retired default anthropic model

helm/agents/istio/templates/agent.yaml
The response format in the instructions is causing odd output, and it doesn't really make any sense.
BEFORE:
AFTER:
=> Remove response format from Istio agent

go/internal/httpserver/handlers/sessions.go
Agent id `agent/ns` that is stored in a session is represented as `agent__NS__ns`. Whereas the same id is represented as `agent/ns` when it comes from the Principal. A check comparing expected agent id vs. current thus always fails.
This PR fixes the issue by normalizing the agent id format before the check to the one used when persisting the id in a db.
=> bugfix: fix comparison of agent ids

ui/src/components/AddServerDialog.tsx, ui/src/lib/__tests__/utils.test.ts
I was trying to add an mcp server with package name `awslabs.terraform-mcp-server@latest` which resulted in invalid server name (the `.` was left in). Switched the implementation to use the createRFC1123ValidName func instead + added unit tests.
=> fix the mcp server naming issue

helm/kagent/values.yaml
The current default model `gemini-1.5-pro` in the Helm `values.yaml` file causes an error during deployment:
```
Model models/gemini-1.5-pro failed: 404 models/gemini-1.5-pro-002 is not found for API version v1beta, or is not supported for generateContent.
```
Issue which i faced:
To resolve this, the default model value has been updated to `gemini-2.0-flash-lite`, which is available and works correctly with the `generateContent` API.
**Changes made:**
* Updated the default value for `providers.openAI.model` (or equivalent key) in `values.yaml` to `gemini-2.0-flash-lite`.
=> Fix: Update default Gemini model in Helm values to gemini-2.0-flash-lite for compatibility

go/Makefile, go/cli/cmd/kagent/main.go, go/cli/internal/cli/agent/invoke.go, go/cli/internal/cli/agent/utils.go
This PR prints out the `kagent` version even if a port-forwarding to the `kagent` server fails. In case the port-forwarding does not succeed, the unavailable versions will be marked as `<unknown>`:
Fixes: https://github.com/kagent-dev/kagent/issues/868
Related to: https://github.com/kagent-dev/kagent/pull/879
```sh
> go run cli/cmd/kagent/main.go version
Error starting port-forward: failed to establish connection to kagent-controller. error connecting to server. Please run 'install' command first
{"backend_version":"unknown","build_date":"unknown","git_commit":"none","kagent_version":"dev"}
```
~~**Note:** We might can consider removing the error message as it breaks the `json` output ...~~
Furthermore: 
- This PR uses `cmd.Context()` consistently throughout all `kagent` subcommands.
- It …
=> fix(version): print out version regardless of port-forwarding; pass through contexts 
